export const getSpecial = (x: number, y: number) => ({
  x,
  y,
  x2: y ** 2,
  y2: x ** 2,
  x3: x ** 3,
  y3: y ** 3,
  xy: x * y,
  xy2: x * y ** 2,
  x2y: y * x ** 2,
  sx: Math.sin(x),
  cx: Math.cos(x),
  sy: Math.sin(y),
  cy: Math.cos(y),
});
